language: python
before_install:
- pip install pipreqs && pipreqs ./ --encoding=utf8 --force
- mkdir data
install: pip install -r requirements.txt
script: python3 main.py
deploy:
  provider: releases
  token: d0e425292ab39d789924dcc11408f8e571f7f86e
  file_glob: true
  file: data/*
  cleanup: false
  overwrite: true
